version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      dev-deps-minor:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'ci'
    groups:
      gh-actions:
        patterns:
          - '*'
